### ISSUE TITLE
无法启动内核

### ISSUE THREAD

**Issue by a520ass** [PuXiongfei/phicomm-n1-armbian#1]
大佬你好，使用的是Armbian_2022.04.28-PuXiongfei_Phicomm-n1_bullseye_edge_5.17.5.img
写入到u盘，未做任何修改，上电后，到启动内核的阶段，就直接循环重启。
是哪里需要修改吗，也没看到哪个文件指定了dtb文件

**Comment by PuXiongfei** [comment]
> 大佬你好，使用的是Armbian_2022.04.28-PuXiongfei_Phicomm-n1_bullseye_edge_5.17.5.img 写入到u盘，未做任何修改，上电后，到启动内核的阶段，就直接循环重启。 是哪里需要修改吗，也没看到哪个文件指定了dtb文件

你好，很久没有折腾了，我这个是自己向Armbian官方的编译工程里加入了N1相关的内容，然后去编译的，自己有试过是可以正常U盘引导并且写入EMMC中使用，可能随着Armbian的更新，里面有些补丁啥的不适用了，你可以直接Fork走，自己编译看看有无报错这些。
